const happyHuesPalletes = {
    "one": {
        primary: "#f3d2c1",
        secondary: "#f582ae",
        tertiary: "#f582ae",
        highlight: "#fef6e4",
        bg: "#fef6e4",
        cardBg: "#f9e8c9",
        text: "#172c66",
        border: "#001858",
        shadow: "#f3d2c1",





    },
    "two": {
        bg: "#271c19",
        cardBg: "#55423d",
        headline: "#fffffe",
        text: "#fff3ec",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "three": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "four": {

        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "five": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "six": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "seven": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "eight": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "nine": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "ten": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "eleven": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "twelve": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "thirteen": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "fourteen": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "fifteen": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "sixteen": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },
    "seventeen": {
        bg: "",
        cardBg: "",
        headline: "",
        text: "",
        btn: "",
        btnText: "",
        primary: "",
        secondary: "",
        tertiary: "",
        highlight: "",
        stroke: ""
    },


}


